f[ii]{k:x*y;k}
//f[1;1]
\\
/z[i]{n:0;W(x>1){x:$[x&1;(\x)+x+1;/x];n+:1};n}
/18=z[30]
/\\
/r[I]{n:#x;h:/#x;c:0;N(h){t:x[i];j:-1+n-i;x[i]:x[j];x[j]:t};x}
/x:!10
/r[x]
/\\
/\\
/b[Ii]{h:#x;l:0;W(h>l)$[y>x[i:/l+h];l:i+1;h:i];l}
/\\
m[i]{k:0;N(x){r:-1.5+2*i%x;N(x){s:-1+2*j%x;p:q:0.;m:50;W(m*4>(t:p*p)+u:q*q){m-:1;q:s+2*p*q;p:r+t-u};k+:0=m}};k}
m[100]
\\
